### ISSUE TITLE
Simpler keys

### ISSUE THREAD

**Issue by andreas-roehler** [purcell/default-text-scale#10]
Great package, thanks.
These keys work here and seem more natural:
```
;; (define-key map (kbd "C-M-=") 'default-text-scale-increase)
;; (define-key map (kbd "C-M--") 'default-text-scale-decrease)
(define-key map (kbd "C-+") 'default-text-scale-increase)
(define-key map (kbd "C--") 'default-text-scale-decrease)

```

**Comment by purcell** [comment]
I'd definitely encourage you to change keybindings to whatever you prefer: that's the beauty of Emacs! IIRC, your suggested bindings clash with those of `expand-region.el`.
