### ISSUE TITLE
Modeline is not updated after font size change

### ISSUE THREAD

**Issue by david-alvarez-rosa** [purcell/default-text-scale#13]
Emacs mode line is not being updated after triggering a increase/decrease of the default text scale.  The font of the mode line is being updated, but not the "format" of it.

View screenshot before:
<img width="1512" alt="Screenshot 2022-09-18 at 14 23 17" src="https://user-images.githubusercontent.com/77437099/190901967-b14969a7-e556-4200-bbac-d4934ff48f59.png">

And screenshot after increasing font size:
<img width="1512" alt="Screenshot 2022-09-18 at 14 23 31" src="https://user-images.githubusercontent.com/77437099/190901966-251e81c8-3480-4b02-8c3d-01320ed328a3.png">

The right side of the mode line is being cut because of the font size increase.  I'm not able to find how to trigger a mode line refresh/redraw or similar that works.  Thank you in advance.

**Comment by purcell** [comment]
Hard to say... depends on how that 3rd party modeline calculates its layout. What's the modeline?

**Comment by david-alvarez-rosa** [comment]
Modeline I'm using is [doom-modeline](https://github.com/seagle0128/doom-modeline).  Does that help?

**Comment by purcell** [comment]
That seems to rely on intercepting all sorts of events in order to recalculate widths. I'm guessing you'd need to call `doom-modeline-refresh-font-width-cache` at the appropriate time.

**Comment by david-alvarez-rosa** [comment]
Thank you, @purcell — Calling `doom-modeline-refresh-font-width-cache` just after an update of text scale solves my issue :)  Link to [config](https://github.com/david-alvarez-rosa/dotfiles/blob/master/.config/emacs/README.org#font) update.

Closing ticket.

**Comment by purcell** [comment]
You could probably just add an `:after` advice to `default-text-scale-increment`, then you don't need your own wrapper commands.

**Comment by david-alvarez-rosa** [comment]
True, much simpler, I've updated to follow that. Thank you :)
