### ISSUE TITLE
Creating a new window (make-frame-command) doesn't use the current text scale

### ISSUE THREAD

**Issue by ideasman42** [purcell/default-text-scale#3]
With scaled text run `make-frame-command`, this uses the default font size.

If this is intended behavior, keeping the current font size would be useful as a preference.

**Comment by purcell** [comment]
That's not the intended behaviour, but this case actually works fine for me. Can you provide info about your platform, and minimal steps to reproduce, starting from `emacs -Q` so no customisation or init files are loaded? (You can `M-x load-file`, load the `default-text-scale.el` from the `~/.emacs.d/elpa` directory, and enable `default-text-scale-mode`.)

**Comment by SunDawning** [comment]
Actually it is not a bug, "default-text-scale" works great for me.

Put this in your init.el:

```
(when (display-multi-font-p (selected-frame))
  (default-text-scale-increment
    (- 160
       (face-attribute 'default :height))))
```

And 160 means 16px font-size, change it by yourself.

Similiar question: https://www.reddit.com/r/emacs/comments/8bb6ko/simple_elisp_question_beginner/

**Comment by ideasman42** [comment]
Tracked the issue down, it's caused by setting the default font.
eg:
```
(set-face-attribute 'default nil :font "Source Code Pro Medium")
```

**Comment by ideasman42** [comment]
Found this works:

```
  (add-hook
    'after-make-frame-functions
    (lambda (f) (default-text-scale-increment 0)))
```

With this, `(set-face-attribute 'default nil :font "Source Code Pro Medium")` doesn't make new windows get the wrong size.

Could this be added to `default-text-scale` ?
